"""Simulations de carnets d'ordres limites (LOB) et estimateurs d'événements rares."""

from model.lob import LOBState
from model.events import Event, EventType
from model.ogata import (
    Checkpoint,
    Trajectory,
    IndependentPoissonSimulator,
    SingleHawkesSimulator,
    CoupledHawkesSimulator,
    FourQueueHawkesSimulator,
)
from model.rare_events import (
    RareEventProblem,
    q1_depletion_problem,
    ask_best_depletion_problem,
    bid_best_depletion_problem,
    min_best_depletion_problem,
    first_limit_depletion_problem,
    imbalance_crossing_problem,
    second_limit_activation_problem,
    q2_after_q1_depletion_problem,
)
from model.splitting import (
    SplittingResult,
    AMSResult,
    FixedLevelSplitting,
    AdaptiveMultilevelSplitting,
)
from model.restart_splitting import (
    METHOD_NAME,
    NAIVE_METHOD_NAME,
    MarkovState,
    BoundaryCheckpoint,
    BoundarySample,
    RestartSplittingResult,
    MultilevelRestartSplittingResult,
    default_hawkes_burn_in,
    queue_boundary_fn,
    local_depletion_target_fn,
    local_recovery_fn,
    checkpoint_to_markov_state,
    markov_state_to_checkpoint,
    extract_excitation_vector,
    collect_boundary_states,
    restart_from_boundary_distribution,
    run_naive_depletion_monte_carlo,
    multilevel_markovian_restart_splitting,
    bootstrap_mean_ci,
    bootstrap_difference_ci,
    run_naive_boundary_mc,
    summarize_conditional_S,
    plot_conditional_S_marginals,
    plot_conditional_S_pairwise,
    plot_conditional_S_heatmap,
)
from model.plotting_utils import (
    safe_barplot_metric,
    plot_hist_with_ci,
    plot_delta_with_ci,
    plot_joint_scatter_or_hexbin,
    format_metric_table,
)
from model import analysis
from model import hitting_times
from model.analysis import run_markovian_conditional_restart_splitting
from model.hitting_times import (
    HittingTimeResult,
    simulate_until_hit_zero,
    simulate_brownian_until_hit_zero,
    hitting_time_pdf_brownian,
    hitting_time_cdf_brownian,
    hitting_time_mean_brownian,
    hitting_time_variance_brownian,
    prob_q1_hits_first_brownian,
    batch_hitting_times,
    scan_initial_conditions,
)

__all__ = [
    "LOBState",
    "Event",
    "EventType",
    "Checkpoint",
    "Trajectory",
    "IndependentPoissonSimulator",
    "SingleHawkesSimulator",
    "CoupledHawkesSimulator",
    "FourQueueHawkesSimulator",
    "RareEventProblem",
    "q1_depletion_problem",
    "ask_best_depletion_problem",
    "bid_best_depletion_problem",
    "min_best_depletion_problem",
    "first_limit_depletion_problem",
    "imbalance_crossing_problem",
    "second_limit_activation_problem",
    "q2_after_q1_depletion_problem",
    "SplittingResult",
    "AMSResult",
    "FixedLevelSplitting",
    "AdaptiveMultilevelSplitting",
    "METHOD_NAME",
    "NAIVE_METHOD_NAME",
    "MarkovState",
    "BoundaryCheckpoint",
    "BoundarySample",
    "RestartSplittingResult",
    "MultilevelRestartSplittingResult",
    "default_hawkes_burn_in",
    "queue_boundary_fn",
    "local_depletion_target_fn",
    "local_recovery_fn",
    "checkpoint_to_markov_state",
    "markov_state_to_checkpoint",
    "extract_excitation_vector",
    "collect_boundary_states",
    "restart_from_boundary_distribution",
    "run_naive_depletion_monte_carlo",
    "multilevel_markovian_restart_splitting",
    "bootstrap_mean_ci",
    "bootstrap_difference_ci",
    "run_naive_boundary_mc",
    "summarize_conditional_S",
    "plot_conditional_S_marginals",
    "plot_conditional_S_pairwise",
    "plot_conditional_S_heatmap",
    "safe_barplot_metric",
    "plot_hist_with_ci",
    "plot_delta_with_ci",
    "plot_joint_scatter_or_hexbin",
    "format_metric_table",
    "run_markovian_conditional_restart_splitting",
    "analysis",
    "hitting_times",
    "HittingTimeResult",
    "simulate_until_hit_zero",
    "simulate_brownian_until_hit_zero",
    "hitting_time_pdf_brownian",
    "hitting_time_cdf_brownian",
    "hitting_time_mean_brownian",
    "hitting_time_variance_brownian",
    "prob_q1_hits_first_brownian",
    "batch_hitting_times",
    "scan_initial_conditions",
]
